### ISSUE TITLE
Translating multiple objects by selecting multiple nodes

### ISSUE THREAD

**Issue by fpmalard** [petrbroz/vscode-forge-tools#26]
![Screen Shot 2020-06-10 at 13 50 33](https://user-images.githubusercontent.com/818592/84296456-6c27b200-ab22-11ea-9e67-550d687ae27a.jpg)

**Comment by petrbroz** [comment]
Good idea, the same functionality would be nice for other operations as well, e.g., deleting multiple objects. I'll need to see if vscode API supports multi-selection.

**Comment by petrbroz** [comment]
Still waiting to hear back from vscode but at this point it looks like there's no official support for handling multi-selections in custom trees: https://github.com/microsoft/vscode/issues/99767.

**Comment by ofcdesk** [comment]
What if you do per bucket? User right click the bucket then, using the same input box you were using to select mime-type for SVF download, you ask them for a name filter (default to "*.*"). The, via code, you collect the folder objects based on that. Not ideal but since there is no multi-select feature, it could temporarily work.

**Comment by petrbroz** [comment]
Closing this for now. If this kind of feature is requested by more users, we can reopen it.
