### ISSUE TITLE
View extension Autodesk.DocumentBrowser not working

### ISSUE THREAD

**Issue by Lennard92** [petrbroz/vscode-forge-tools#62]
Hi,

first of all tank you for you work here. I just managed to set up the autodesk forge tools extension in vs code and it works fine. Now I want to add the Autodesk.DocumentBrowser to the viewer. How exactly do i do that? I tried it like this, but this doesn't work:

![image](https://user-images.githubusercontent.com/77276454/185140897-f40753b0-e97b-41cf-b322-d81d214d59be.png)

**Comment by Lennard92** [comment]
OK, ich changed nothing and today it works :D Do you know what could be the reason for that?

**Comment by petrbroz** [comment]
Hi @Lennard92, thanks for the heads up! The list of viewer extensions is only read when the VSCode plugin is activated (https://github.com/petrbroz/vscode-forge-tools/blob/develop/src/extension.ts#L60-L64), so I think what happened was this:

1. You activated the VSCode plugin (and it read the list of viewer extensions from the settings).
2. You modified the settings.
3. You tried opening the viewer but the VSCode plugin was still using the settings obtained in step 1.

In the future we may consider updating the plugin so that it always reads _fresh_ settings, but for now, whenever you change any of the plugin settings, simply reload the VSCode window.
